[package]
name = "fissure_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bytes = "0.11.12"
serde = { version = "1.0", features = ["derive"] }
serde_bencoded = "0.3.1"
